# Generated by Django 4.1.7 on 2025-12-12 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('total_activities', models.IntegerField(default=0)),
                ('total_duration', models.IntegerField(default=0, help_text='Total duration in minutes')),
                ('total_distance', models.FloatField(default=0.0, help_text='Total distance in kilometers')),
                ('total_calories', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leaderboard Entries',
                'db_table': 'leaderboard_entries',
                'ordering': ['-total_calories', '-total_duration'],
                'unique_together': {('user', 'period', 'period_start', 'period_end')},
            },
        ),
    ]
